name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test AOC21 solutions
        run: |
          cd aoc21
          gcc -o runner runner.cpp
          ./runner
