name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2   
      - name: aoc21 solutions
        run: aoc21/build.sh
  build-windows:
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: aoc21 solutions
        shell: cmd
        run: call aoc21\build.cmd
