name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2   
      - name: aoc21 solutions
        run: cd aoc21 && gcc -o runner runner.cpp && ./runner
  build-windows:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2   
      - name: aoc21 solutions
        run: |
          cd aoc21
          for /f "usebackq tokens=*" %%i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [16.0^,17.0^) -requires Microsoft.VisualStudio.Workload.NativeDesktop -property installationPath`) do set VS=%%i
          cl runner.cpp && runner
